import { useState } from 'react'
import { useParent } from '../../lib/parentContext'
import { Button } from '../../components/ui'
import { CLUB } from '../../lib/clubInfo'
import { KeyRound, Info, Plus, X } from 'lucide-react'
import tfaLogo from '../../assets/tfa-logo.png'

// Shown when a parent has no linked children yet. Single input takes the
// child's access code (the player's editCode, generated by the coach on
// registration). On success the parent enters the scoped Shell.
//
// Also reused inline by the More tab's "Manage children" sheet to add
// additional children — pass `embedded` to drop the page chrome.
export function ParentLink({ onSwitchRole, embedded = false }) {
  const { addCode, linkedPlayers, removeChild } = useParent()
  const [input, setInput] = useState('')
  const [error, setError] = useState('')
  const [busy, setBusy]   = useState(false)

  async function submit(e) {
    e?.preventDefault?.()
    if (busy) return
    setBusy(true)
    setError('')
    const result = addCode(input)
    setBusy(false)
    if (result.ok) {
      setInput('')
    } else if (result.reason === 'empty') {
      setError('Enter your child’s access code.')
    } else {
      setError('No child found with that code. Check with your coach.')
    }
  }

  const inner = (
    <>
      <div className="rounded-2xl border border-white/[0.08] bg-white/[0.03] p-5">
        <div className="flex items-center gap-3 mb-4">
          <div className="inline-flex h-10 w-10 items-center justify-center rounded-xl bg-gold/15 border border-gold/30">
            <KeyRound size={18} className="text-gold" />
          </div>
          <div>
            <div className="font-condensed font-bold uppercase tracking-[0.14em] text-[10px] text-gold">
              {linkedPlayers.length === 0 ? 'Link your child' : 'Add another child'}
            </div>
            <div className="font-display font-bold uppercase text-cream text-xl" style={{ lineHeight: 0.9 }}>
              Enter access code
            </div>
          </div>
        </div>

        <form onSubmit={submit} className="flex flex-col gap-3">
          <input
            autoFocus
            value={input}
            onChange={e => { setInput(e.target.value); setError('') }}
            placeholder="ABC123"
            autoCapitalize="characters"
            autoCorrect="off"
            spellCheck={false}
            inputMode="text"
            maxLength={12}
            className="w-full h-12 px-4 rounded-md bg-navy-soft border border-white/[0.1] text-cream font-display text-xl tracking-[0.3em] uppercase text-center focus:outline-none focus:border-gold"
          />
          {error && (
            <div className="font-condensed text-[11.5px] text-red-400 text-center">{error}</div>
          )}
          <Button variant="primary" size="md" type="submit" disabled={busy || !input.trim()}>
            {linkedPlayers.length === 0 ? 'Link child' : 'Add child'}
          </Button>
        </form>

        <div className="flex items-start gap-2 mt-4 font-body text-[12.5px] text-muted leading-snug">
          <Info size={12} className="mt-1 flex-none text-faint" />
          <span>
            Don’t have a code? Ask {CLUB.coachName} to send your child’s access code via LINE.
          </span>
        </div>
      </div>

      {linkedPlayers.length > 0 && (
        <div className="rounded-2xl border border-white/[0.06] bg-white/[0.02] p-4">
          <div className="font-condensed font-bold uppercase tracking-[0.14em] text-[10.5px] text-muted mb-2">
            Linked children
          </div>
          <div className="flex flex-col gap-1.5">
            {linkedPlayers.map(p => (
              <div key={p.id} className="flex items-center gap-3 px-3 py-2 rounded-lg bg-white/[0.03] border border-white/[0.05]">
                <div className="flex-1 min-w-0">
                  <div className="font-body text-sm text-cream truncate">{p.name}</div>
                  <div className="font-condensed font-bold uppercase tracking-[0.06em] text-[10px] text-muted">
                    {p.ageGroup} · {p.position}
                  </div>
                </div>
                <button
                  type="button"
                  onClick={() => removeChild(p.id)}
                  aria-label={`Unlink ${p.name}`}
                  className="w-8 h-8 rounded-full border border-white/[0.1] text-faint flex items-center justify-center transition-all duration-fast active:scale-[0.94]"
                >
                  <X size={14} />
                </button>
              </div>
            ))}
          </div>
        </div>
      )}
    </>
  )

  if (embedded) return <div className="flex flex-col gap-3.5">{inner}</div>

  return (
    <div className="min-h-screen w-full flex flex-col items-center px-5 py-8">
      <div className="flex items-center gap-3 mb-6">
        <img src={tfaLogo} alt="TFA" className="h-12 w-auto" />
        <div>
          <div className="font-condensed font-bold uppercase tracking-[0.2em] text-[10px] text-muted">
            The Football Academy
          </div>
          <div className="font-display font-bold uppercase text-cream text-[26px]" style={{ lineHeight: 0.9 }}>
            Parent access
          </div>
        </div>
      </div>

      <div className="w-full max-w-[420px] flex flex-col gap-3.5">
        {inner}

        {onSwitchRole && (
          <button
            type="button"
            onClick={onSwitchRole}
            className="mt-2 w-full px-4 h-11 rounded-md border border-white/[0.1] text-muted font-condensed font-bold uppercase tracking-[0.14em] text-xs"
          >
            Switch role
          </button>
        )}
      </div>
    </div>
  )
}

// Helper used by ParentMore — same component, embedded layout.
export function ParentLinkEmbedded() {
  return <ParentLink embedded />
}
